// <auto-generated />
using System;
using JacisCrochetCreations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JacisCrochetCreations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("JacisCrochetCreations.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("JacisCrochetCreations.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Scarf",
                            Description = "A warm and cozy striped crochet scarf with soft textured stitches.",
                            ImageUrl = "/img/cozystripedscarf.png",
                            Name = "Cozy Striped Scarf",
                            Price = 25m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Scarf",
                            Description = "Rich berry-toned scarf perfect for winter outfits.",
                            ImageUrl = "/img/winterberryscarf.png",
                            Name = "Winter Berry Scarf",
                            Price = 28m,
                            Stock = 12
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Scarf",
                            Description = "A light pastel-colored scarf ideal for springtime weather.",
                            ImageUrl = "/img/pastelbreezescarf.png",
                            Name = "Pastel Breeze Scarf",
                            Price = 22m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Scarf",
                            Description = "A gradient scarf fading from golden yellow to deep rose tones.",
                            ImageUrl = "/img/sunsetfadescarf.png",
                            Name = "Sunset Fade Scarf",
                            Price = 30m,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Scarf",
                            Description = "Extra-thick chunky crochet scarf for ultimate warmth and comfort.",
                            ImageUrl = "/img/chunkycomfortscarf.png",
                            Name = "Chunky Comfort Scarf",
                            Price = 35m,
                            Stock = 8
                        },
                        new
                        {
                            ProductId = 6,
                            Category = "Bag",
                            Description = "A compact everyday pouch with a secure crochet finish.",
                            ImageUrl = "/img/minicrossbodybag.png",
                            Name = "Mini Crossbody Pouch",
                            Price = 15m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 7,
                            Category = "Bag",
                            Description = "A sturdy handmade tote bag perfect for grocery runs and errands.",
                            ImageUrl = "/img/markettote.png",
                            Name = "Market Tote Bag",
                            Price = 30m,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 8,
                            Category = "Bag",
                            Description = "A colorful boho-inspired crocheted shoulder bag with long fringe.",
                            ImageUrl = "/img/crochetbohofringebag.png",
                            Name = "Boho Fringe Shoulder Bag",
                            Price = 40m,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 9,
                            Category = "Bag",
                            Description = "A vibrant bag created from traditional multicolor granny squares.",
                            ImageUrl = "/img/floralgrannysquarebag.png",
                            Name = "Floral Granny Square Bag",
                            Price = 35m,
                            Stock = 8
                        },
                        new
                        {
                            ProductId = 10,
                            Category = "Bag",
                            Description = "Striped tote bag perfect for sunny beach days and vacations.",
                            ImageUrl = "/img/summerstripebeachbag.png",
                            Name = "Summer Stripe Beach Bag",
                            Price = 32m,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 11,
                            Category = "Plushie",
                            Description = "A soft handmade amigurumi bunny wearing a striped sweater.",
                            ImageUrl = "/img/crochetbunnyplushie.png",
                            Name = "Cozy Bunny Plush",
                            Price = 20m,
                            Stock = 18
                        },
                        new
                        {
                            ProductId = 12,
                            Category = "Plushie",
                            Description = "A peaceful amigurumi bear with adorable sleepy eyes.",
                            ImageUrl = "/img/sleepybearplush.png",
                            Name = "Sleepy Bear Plush",
                            Price = 22m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 13,
                            Category = "Plushie",
                            Description = "A small green dinosaur plush perfect for kids and collectors.",
                            ImageUrl = "/img/dinosaurplush.png",
                            Name = "Tiny Dinosaur Plush",
                            Price = 18m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 14,
                            Category = "Plushie",
                            Description = "A soft pastel-colored crocheted kitten plushie.",
                            ImageUrl = "/img/pastelkitten.png",
                            Name = "Pastel Kitten Plush",
                            Price = 20m,
                            Stock = 14
                        },
                        new
                        {
                            ProductId = 15,
                            Category = "Plushie",
                            Description = "A cute pink-and-white amigurumi cow with strawberry accents.",
                            ImageUrl = "/img/strawberrycow.png",
                            Name = "Strawberry Cow Plush",
                            Price = 25m,
                            Stock = 12
                        },
                        new
                        {
                            ProductId = 16,
                            Category = "Sweater",
                            Description = "A warm oversized crochet cardigan perfect for layering.",
                            ImageUrl = "/img/cozycardigan.jpg",
                            Name = "Cozy Cardigan",
                            Price = 55m,
                            Stock = 6
                        },
                        new
                        {
                            ProductId = 17,
                            Category = "Sweater",
                            Description = "A colorful granny-square inspired patchwork sweater.",
                            ImageUrl = "/img/vintagepatchworksweater.png",
                            Name = "Vintage Patchwork Sweater",
                            Price = 60m,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 18,
                            Category = "Sweater",
                            Description = "A warm striped pullover inspired by fall colors.",
                            ImageUrl = "/img/autumnstripessweater.jpg",
                            Name = "Autumn Stripes Pullover",
                            Price = 50m,
                            Stock = 7
                        },
                        new
                        {
                            ProductId = 19,
                            Category = "Sweater",
                            Description = "A trendy lavender crochet cropped sweater.",
                            ImageUrl = "/img/lavendersweater.jpg",
                            Name = "Lavender Cropped Sweater",
                            Price = 45m,
                            Stock = 9
                        },
                        new
                        {
                            ProductId = 20,
                            Category = "Sweater",
                            Description = "A classic textured crochet sweater in soft teal yarn.",
                            ImageUrl = "/img/tealcablesweater.jpg",
                            Name = "Teal Cable Sweater",
                            Price = 65m,
                            Stock = 4
                        },
                        new
                        {
                            ProductId = 21,
                            Category = "Blanket",
                            Description = "A super soft pastel baby blanket with gentle stitching.",
                            ImageUrl = "/img/crochetbabyblanket.png",
                            Name = "Baby Soft Blanket",
                            Price = 45m,
                            Stock = 8
                        },
                        new
                        {
                            ProductId = 22,
                            Category = "Blanket",
                            Description = "A large warm throw blanket for living room comfort.",
                            ImageUrl = "/img/cozythrowblanket.jpg",
                            Name = "Cozy Throw Blanket",
                            Price = 55m,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 23,
                            Category = "Blanket",
                            Description = "A brightly colored rainbow striped crochet blanket.",
                            ImageUrl = "/img/rainbowburst.jpg",
                            Name = "Rainbow Burst Blanket",
                            Price = 60m,
                            Stock = 4
                        },
                        new
                        {
                            ProductId = 24,
                            Category = "Blanket",
                            Description = "A minimalist cream and taupe aesthetic crochet blanket.",
                            ImageUrl = "/img/neutralblanket.jpg",
                            Name = "Neutral Aesthetic Blanket",
                            Price = 50m,
                            Stock = 6
                        },
                        new
                        {
                            ProductId = 25,
                            Category = "Blanket",
                            Description = "A handmade granny-square blanket with colorful patchwork.",
                            ImageUrl = "/img/grannysquareblanket.jpg",
                            Name = "Granny Square Patch Blanket",
                            Price = 65m,
                            Stock = 3
                        });
                });

            modelBuilder.Entity("JacisCrochetCreations.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Content = "So soft and warm! The colors look even better in person.",
                            Name = "Emily",
                            PostedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 2,
                            Content = "Perfect length and super comfy. Ships fast too!",
                            Name = "Sarah",
                            PostedOn = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 1,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 3,
                            Content = "The berry colors are gorgeous! Very festive.",
                            Name = "Jordan",
                            PostedOn = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 4,
                            Content = "Warm enough for cold mornings. Great stitch work.",
                            Name = "Mia",
                            PostedOn = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 5,
                            Content = "The pastel shades are dreamy!",
                            Name = "Lily",
                            PostedOn = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 6,
                            Content = "Lightweight and perfect for spring.",
                            Name = "Kate",
                            PostedOn = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 3,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 7,
                            Content = "The gradient is stunning. Truly handmade beauty.",
                            Name = "Ava",
                            PostedOn = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 8,
                            Content = "I get compliments every time I wear it.",
                            Name = "Hannah",
                            PostedOn = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 4,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 9,
                            Content = "So chunky and cozy – it’s like wearing a cloud.",
                            Name = "Olivia",
                            PostedOn = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 10,
                            Content = "Warm and stylish, perfect for winter.",
                            Name = "Beth",
                            PostedOn = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 11,
                            Content = "Perfect little bag for on-the-go!",
                            Name = "Chloe",
                            PostedOn = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 6,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 12,
                            Content = "Fits my phone and keys. Super cute.",
                            Name = "Grace",
                            PostedOn = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 6,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 13,
                            Content = "Strong enough for groceries!",
                            Name = "Nora",
                            PostedOn = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 7,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 14,
                            Content = "Very durable and stylish.",
                            Name = "Jade",
                            PostedOn = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 7,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 15,
                            Content = "The fringe is everything – total boho vibes.",
                            Name = "Riley",
                            PostedOn = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 8,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 16,
                            Content = "Spacious and unique. Love it!",
                            Name = "Tessa",
                            PostedOn = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 8,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 17,
                            Content = "Beautiful craftsmanship and colors.",
                            Name = "Hope",
                            PostedOn = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 9,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 18,
                            Content = "So colorful and cheerful. My favorite bag now.",
                            Name = "Lauren",
                            PostedOn = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 9,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 19,
                            Content = "Holds towels, sunscreen, snacks – amazing.",
                            Name = "Isla",
                            PostedOn = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 10,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 20,
                            Content = "Bright and summery!",
                            Name = "Zoey",
                            PostedOn = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 10,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 21,
                            Content = "Cutest bunny ever – so soft!",
                            Name = "Paige",
                            PostedOn = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 11,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 22,
                            Content = "Perfect gift for my niece.",
                            Name = "Ella",
                            PostedOn = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 11,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 23,
                            Content = "The sleepy eyes are adorable.",
                            Name = "Maddie",
                            PostedOn = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 12,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 24,
                            Content = "Great bedtime plush for kids.",
                            Name = "Sophie",
                            PostedOn = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 12,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 25,
                            Content = "Tiny and cute – perfect desk buddy.",
                            Name = "Leo",
                            PostedOn = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 13,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 26,
                            Content = "My son carries it everywhere.",
                            Name = "Ethan",
                            PostedOn = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 13,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 27,
                            Content = "The pastel colors are precious.",
                            Name = "Aria",
                            PostedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 14,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 28,
                            Content = "Soft and well-made.",
                            Name = "Naomi",
                            PostedOn = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 14,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 29,
                            Content = "Strawberry cow is everything!",
                            Name = "Daisy",
                            PostedOn = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 15,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 30,
                            Content = "Adorable and unique plush.",
                            Name = "Clara",
                            PostedOn = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 15,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 31,
                            Content = "So warm and oversized. I’m obsessed.",
                            Name = "Hailey",
                            PostedOn = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 16,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 32,
                            Content = "Beautiful yarn texture.",
                            Name = "Jo",
                            PostedOn = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 16,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 33,
                            Content = "Retro and stylish – compliments guaranteed.",
                            Name = "Ivy",
                            PostedOn = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 17,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 34,
                            Content = "Love the colors and patchwork.",
                            Name = "Rae",
                            PostedOn = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 17,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 35,
                            Content = "Perfect fall sweater.",
                            Name = "Bri",
                            PostedOn = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 18,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 36,
                            Content = "Warm and comfy.",
                            Name = "Kara",
                            PostedOn = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 18,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 37,
                            Content = "Cute and trendy. Love the lavender.",
                            Name = "Jess",
                            PostedOn = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 19,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 38,
                            Content = "Perfect with high-waisted jeans.",
                            Name = "Morgan",
                            PostedOn = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 19,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 39,
                            Content = "Gorgeous cable pattern.",
                            Name = "Renee",
                            PostedOn = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 20,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 40,
                            Content = "Very warm and cozy.",
                            Name = "Sky",
                            PostedOn = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 20,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 41,
                            Content = "Perfect baby shower gift – so soft.",
                            Name = "Lena",
                            PostedOn = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 21,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 42,
                            Content = "Gentle and snuggly.",
                            Name = "Becca",
                            PostedOn = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 21,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 43,
                            Content = "Use it every night on the couch.",
                            Name = "Tori",
                            PostedOn = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 22,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 44,
                            Content = "Warm and lovely texture.",
                            Name = "Megan",
                            PostedOn = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 22,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 45,
                            Content = "Bright and cheerful – kids love it.",
                            Name = "Kayla",
                            PostedOn = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 23,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 46,
                            Content = "Beautiful colors and so fun.",
                            Name = "Jay",
                            PostedOn = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 23,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 47,
                            Content = "Fits my room aesthetic perfectly.",
                            Name = "Molly",
                            PostedOn = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 24,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 48,
                            Content = "Soft, cozy, and minimalist.",
                            Name = "Ciara",
                            PostedOn = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 24,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 49,
                            Content = "A work of art – so nostalgic.",
                            Name = "Lori",
                            PostedOn = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 25,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 50,
                            Content = "Colorful and feels handmade with love.",
                            Name = "Dani",
                            PostedOn = new DateTime(2025, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 25,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("JacisCrochetCreations.Models.CartItem", b =>
                {
                    b.HasOne("JacisCrochetCreations.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JacisCrochetCreations.Models.Review", b =>
                {
                    b.HasOne("JacisCrochetCreations.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JacisCrochetCreations.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
